/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
//Left Button
public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:798507:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
} //_CODE_:button1:798507:
//Left Button
public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:223178:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:223178:

//Right Button
public void textarea2_change1(GTextArea source, GEvent event) { //_CODE_:textarea2:256221:
  println("textarea2 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea2:256221:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  ff = new GLabel(this, 775, 70, 80, 20);
  ff.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  ff.setText("MODE 2");
  ff.setOpaque(false);
  button1 = new GButton(this, 60, 49, 80, 30);
  button1.setText("LEFT");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 164, 52, 80, 30);
  button2.setText("RIGHT");
  button2.addEventHandler(this, "button2_click1");
  label3 = new GLabel(this, 117, 21, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("MODE 2");
  label3.setOpaque(false);
  textarea2 = new GTextArea(this, 60, 91, 184, 79, G4P.SCROLLBARS_NONE);
  textarea2.setOpaque(true);
  textarea2.addEventHandler(this, "textarea2_change1");
}

// Variable declarations 
// autogenerated do not edit
GLabel ff; 
GButton button1; 
GButton button2; 
GLabel label3; 
GTextArea textarea2; 
